Add hold-repeat feature
amperka/TroykaButton pull request #2
Opened 2022-09-14 13:59 UTC by gabbapeople

2022-09-14 14:37 UTC, nkrkv requested changes
Ломается обратная совместимость. Стоит новый параметр добавить в конструктор последним.

2022-09-15 13:06 UTC, nkrkv requested changes
Всё ОК. Есть пара занудств

2022-09-15 13:06 UTC, nkrkv commented on src/TroykaButton.cpp
> +        pinMode(_pin, INPUT);
Так короче:

```suggestion
    pinMode(_pin, _pullUP ? INPUT_PULLUP : INPUT);
```

Правильно понимаю, что раньше функциональность была заявлена, но фактически настройка `pullUP` игнорировалась?

2022-09-15 13:06 UTC, nkrkv commented on src/TroykaButton.h
> +    uint8_t _buttonInfoOld;
Зачем переименовывать? Мне кажется слово `state` лучше отражает суть, чем `info`. Или ты, чтобы не путать с `digitalRead`? Можно использовать слово `event` или `eventState`, например.

2022-09-15 13:06 UTC, nkrkv commented on src/TroykaButton.cpp
> +    _buttonInfo = 0;
Эта штука — enum; здесь должна присваиваться `SOME_STATE_NAME`, не литерал нуля

2022-09-15 13:07 UTC, gabbapeople commented on src/TroykaButton.cpp
> +        pinMode(_pin, INPUT);
да

2022-09-15 14:21 UTC, nkrkv approved these changes
LGTM

2022-09-15 14:57 UTC, merged